model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 300  ## Logging: frequency for progressive denoising 
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 64
    channels: 1
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [100] # [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 16
        in_channels: 3
        out_channels: 3
        model_channels: 96
        attention_resolutions: [ 1, 2, 4, 8]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4]  # 32, 16, 8, 4, 2
        num_heads: 4
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: "val/rec_loss"
        ckpt_path: "protons64_ae_disc_logs/2024-08-09T16-34-42_autoencoder_kl_lartpc_64/checkpoints/epoch=000009.ckpt"
        # ckpt_path: "protons64_ae_disc_small_logs/2024-08-29T16-51-34_autoencoder_kl_lartpc_64/checkpoints/last.ckpt"
        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 64
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
          # ch_mult: [1,2,4,8]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
          disc_in_channels: 1       ## Added from AE config  
          # disc_start: 9999999999999 ## Added from AE config 

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 2
    wrap: True
    train:
      target: ldm.data.protons64.protons64Train 
      params:
        size: 64 
        events_per_batch: 128
        num_batches: 1152 ## set by hand (TODO)
    validation:
      target: ldm.data.protons64.protons64Validation
      params:
        size: 64
        events_per_batch: 128
        num_batches: 152 ## set by hand (TODO)

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False
    
    # checkpoint_iter_freq: 
    #   target: main.CheckpointEveryNSteps
    #   params: 
    #     save_step_frequency: 1000  

  trainer:
    benchmark: False 
    # max_steps: 10000
    max_epochs: 10
    val_check_interval: 1000   ## Validation Frequency  